Task3 - Компании и ценные бумаги в JSON
ArturPonomarev/IBSGitTask pull request #3
Opened 2022-12-24 00:47 UTC by ArturPonomarev

2022-12-24 13:14 UTC, SidorovIgorAlex requested changes

2022-12-24 13:14 UTC, SidorovIgorAlex commented on IBSTasks/main/Task3_Organizations/src/Main.java
> +        for (var company : companyList.companies)
Смотри, в целом цикл в цикле можно заменить на стримы таким образом:
companyList.companies.stream().forEach(
                company -> company.securities.stream()
                        .filter(security -> DateTimeUtil.getDateFromStringFormat(security.date,JSON_DATE_FORMAT).isBefore(LocalDate.now()))
                        .forEach(security -> {System.out.format("\tКод: %s\n\tДата истечения: %s\n\tВладелец: %s\n",
                                security.code,security.date,company.name);})
        );

2022-12-24 13:14 UTC, SidorovIgorAlex commented on IBSTasks/main/Task3_Organizations/src/Main.java
> +                case "1":
Касательно большого метода main, то как минимум можно повыносить логику внутри switch в разные методы, чтобы читаемость стала лучше

2022-12-24 13:14 UTC, SidorovIgorAlex commented on IBSTasks/main/Task3_Organizations/src/Main.java
> +        companyList.companies
Еще как вариант рефакторинга кода - это вынести в отдельный метод - данное выражение - companyList.companies.stream()
И передавать в метода Predicate, так как у тебя в двух местах кода, такая вещь встречается + та доработка, что я тебе ниже комментом оставил

2022-12-24 13:14 UTC, SidorovIgorAlex commented on IBSTasks/main/Task3_Organizations/src/Main.java
> +                    System.out.print("\nВведите наименование валюты: ");
Вот тут вообще не понял, у тебя с 98 строки по 116 чисто навороченный цикл в цикл ради проверки валюты?
А не проще сделать так - List.of().contains() и передать туда то что ты введешь с консолки?

2022-12-24 13:14 UTC, SidorovIgorAlex commented on IBSTasks/main/Task3_Organizations/src/Main.java
> +                        for (var correctFormat : NEED_USER_INPUT_FORMATS)
Вместо всего того, что у тебя написано внутри do While можно написать так
String finalUserInput1 = userInput;
                        if (List.of(NEED_USER_INPUT_FORMATS).stream().anyMatch(correctFormat -> DateTimeUtil.CheckDateFormatIsCorrect(finalUserInput1,correctFormat)))
                            System.out.println("Введеный формат не корректен, повторите ввод.");

2022-12-24 13:14 UTC, SidorovIgorAlex commented on IBSTasks/main/Task3_Organizations/src/Main.java
> +                        for (var correctFormat : NEED_USER_INPUT_FORMATS)
либо сначала получить булево выражение, а потом сделать проверку в if

2022-12-24 13:14 UTC, SidorovIgorAlex commented on IBSTasks/main/Task3_Organizations/src/Main.java
> +                        for (var correctFormat : NEED_USER_INPUT_FORMATS)
А лучше все же сразу же задавать листы, а не массивы

2022-12-24 22:00 UTC, ArturPonomarev commented on IBSTasks/main/Task3_Organizations/src/Main.java
> +        for (var company : companyList.companies)
К сожалению не получится т.к. там участвует переменная oldSecuritySum, которую нельзя изменять в лямбдах

2022-12-25 07:47 UTC, SidorovIgorAlex commented on IBSTasks/main/Task3_Organizations/src/Main.java
> +        for (var company : companyList.companies)
А если сделать через AtomicIteger?

2022-12-27 09:19 UTC, merged